openapi: 3.0.2
info:
  version: 0.0.0-replace
  title: CenterEdge Software Paytronix Integration API
  contact:
    name: Brant Burnett
    email: bburnett@centeredgesoftware.com
  license:
    name: See license agreement
    url: http://paytronix.com/
  x-logo:
    url: 'https://raw.githubusercontent.com/CenterEdge/centeredge-resources/master/logo/2022/CenterEdge_Logo_Cmyk.svg'
  description: CenterEdge Software Integration with Paytronix API
servers:
- url: 'http://example.com/api/v1'
paths:
  '/check/post':
    $ref: 'paths/check/post.yaml'
  '/check/redeemOnly':
    $ref: 'paths/check/redeemOnly.yaml'
  '/check/postAndAccruePoints':
    $ref: 'paths/check/postAndAccruePoints.yaml'
  '/check/postAndAccruePointsWithRedeem':
    $ref: 'paths/check/postAndAccruePointsWithRedeem.yaml'
  '/check/simulateAccrualAndRedemption':
    $ref: 'paths/check/simulateAccrualAndRedemption.yaml'
  '/enrollment/smsEnroll':
    $ref: 'paths/enrollment/smsEnroll.yaml'
  '/enrollment/createAndRegister':
    $ref: 'paths/enrollment/createAndRegister.yaml'
  '/enrollment/addRelatedGuests':
    $ref: 'paths/enrollment/addRelatedGuests.yaml'
  '/enrollment/createEClubAndRegister':
    $ref: 'paths/enrollment/createEClubAndRegister.yaml'
  '/transaction/activateAdd':
    $ref: 'paths/transaction/activateAdd.yaml'
  '/transaction/addRedeem':
    $ref: 'paths/transaction/addRedeem.yaml'
  '/transaction/balanceInquiry':
    $ref: 'paths/transaction/balanceInquiry.yaml'
  '/transaction/reverse':
    $ref: 'paths/transaction/reverse.yaml'
  '/transaction/accountQuery':
    $ref: 'paths/transaction/accountQuery.yaml'
components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
