openapi: 3.0.2
info:
  version: 0.0.0-replace
  title: CenterEdge Software Paytronix Integration API
  contact:
    name: Brant Burnett
    email: bburnett@centeredgesoftware.com
  license:
    name: See license agreement
  x-logo:
    url: 'https://raw.githubusercontent.com/CenterEdge/centeredge-resources/master/logo/2022/CenterEdge_Logo_Cmyk.svg'
  description: >
  CenterEdge Software Integration with Paytronix API
servers:
  - url: 'http://example.com/api/v1'
paths:
  '/check/post':
    $ref: 'paths/check/post.yaml'
  '/check/postAndAccruePointsWithRedeem':
    $ref: 'paths/check/postAndAccruePointsWithRedeem.yaml'
  '/check/simulateAccrualAndRedemption':
    $ref: 'paths/check/simulateAccrualAndRedemption.yaml'
  '/enrollment/smsEnroll':
    $ref: 'paths/enrollment/smsEnroll.yaml'
  '/transaction/reverse':
    $ref: 'paths/transaction/reverse.yaml' 
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
