name: Build

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build - Spec & Yardarm SDK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x # for GitVersion

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1
      with:
        versionSpec: "5.12.0"

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1
      with:
        useConfigFile: true
        configFilePath: "GitVersion.yml"

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Set Version
      run: sed -i 's/0.0.0-replace/${{ steps.gitversion.outputs.legacySemVerPadded }}/g' openapi/openapi.yaml

    - name: Restore
      run: npm ci

    - name: Test
      run: npm run test

    - name: Build - Spec
      run: npm run build

    - name: Upload - Spec
      uses: actions/upload-artifact@v4
      with:
        name: spec
        path: |
          dist

    - name: Build - Yardarm SDK
      uses: CenterEdge/yardarm-action@v1
      with:
        yardarm: 0.5.0-beta0002
        pre-release: true
        args: |
          yardarm generate -i ./dist/centeredge-paytronixapi.yaml -f net6.0 netstandard2.0 --embed --nupkg ./dist/ -n CenterEdge.PaytronixApi -v ${{ steps.gitversion.outputs.nuGetVersionV2 }} -x Yardarm.SystemTextJson Yardarm.MicrosoftExtensionsHttp --repository-url https://github.com/${GITHUB_REPOSITORY}.git --repository-commit ${GITHUB_SHA}

    - name: Setup - CenterEdge Nuget
      uses: centeredge/ci-actions/dotnet/setup/nuget-feed@v1
      with:
        gh-packages-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push - Yardarm SDK
      run: dotnet nuget push **/*.${{ steps.gitversion.outputs.nuGetVersionV2 }}.nupkg -k ${{ secrets.GITHUB_TOKEN  }} -s github
